import type { WordPair } from "./types";

// Word pairs for Undercover, all written in English (Latin script) but chosen to
// be viral / very well-known on Thai social media. Each pair is two *related but
// different* things — that ambiguity is what makes the game fun. The gloss is a
// short hint shown privately to the player who holds that word.
//
// The app randomly picks one pair per game and randomly decides which side is
// the Civilians' word vs the Undercover word, so it's never predictable.
export const WORD_PAIRS: WordPair[] = [
  // ---- Thai actors / BL & GL & lakorn stars ----
  { civilian: "Bright", civilianGloss: "Bright Vachirawit, star of 2gether (BL)", undercover: "Win", undercoverGloss: "Win Metawin, his 2gether co-star (BL)" },
  { civilian: "Mew", civilianGloss: "Mew Suppasit, TharnType lead (BL)", undercover: "Gulf", undercoverGloss: "Gulf Kanawut, his TharnType co-star (BL)" },
  { civilian: "Tay", civilianGloss: "Tay Tawan, BL actor (Dark Blue Kiss)", undercover: "New", undercoverGloss: "New Thitipoom, his BL co-star" },
  { civilian: "Off", civilianGloss: "Off Jumpol, BL actor", undercover: "Gun", undercoverGloss: "Gun Atthaphan, his BL co-star" },
  { civilian: "Earth", civilianGloss: "Earth Pirapat, BL actor", undercover: "Mix", undercoverGloss: "Mix Sahaphap, his BL co-star" },
  { civilian: "Pond", civilianGloss: "Pond Naravit, BL actor", undercover: "Phuwin", undercoverGloss: "Phuwin Tangsakyuen, his BL co-star" },
  { civilian: "Joong", civilianGloss: "Joong Archen, young BL actor", undercover: "Dunk", undercoverGloss: "Dunk Natachai, his BL co-star" },
  { civilian: "First", civilianGloss: "First Kanaphan, BL actor", undercover: "Khaotung", undercoverGloss: "Khaotung Thanawat, his BL co-star" },
  { civilian: "Freen", civilianGloss: "Freen Sarocha, GAP the Series (GL)", undercover: "Becky", undercoverGloss: "Becky Armstrong, her GL co-star" },
  { civilian: "Engfa", civilianGloss: "Engfa Waraha, Miss Grand singer/idol", undercover: "Charlotte", undercoverGloss: "Charlotte Austin, her viral 'EngLot' pair" },
  { civilian: "Nadech", civilianGloss: "Nadech Kugimiya, A-list Thai actor", undercover: "Mario", undercoverGloss: "Mario Maurer, Thai heartthrob actor" },
  { civilian: "Yaya", civilianGloss: "Yaya Urassaya, lakorn queen", undercover: "Bella", undercoverGloss: "Bella Ranee, lakorn queen" },
  { civilian: "Mai Davika", civilianGloss: "Mai Davika, Thai actress (Pee Mak)", undercover: "Kimberley", undercoverGloss: "Kimberley Voltemas, Thai actress" },
  { civilian: "Mark Prin", civilianGloss: "Mark Prin, Thai lakorn lead", undercover: "James Jirayu", undercoverGloss: "James Jirayu, Thai lakorn lead" },
  { civilian: "Nine Naphat", civilianGloss: "Nine Naphat, young Thai heartthrob", undercover: "Nani Hirunkit", undercoverGloss: "Nani Hirunkit, young Thai actor" },

  // ---- Singers / bands / idol groups (T-pop, K-pop, global) ----
  { civilian: "Lisa", civilianGloss: "BLACKPINK's Thai member, rapper-dancer", undercover: "Rosé", undercoverGloss: "BLACKPINK's main vocalist" },
  { civilian: "Jennie", civilianGloss: "BLACKPINK rapper/vocalist", undercover: "Jisoo", undercoverGloss: "BLACKPINK visual/vocalist" },
  { civilian: "BLACKPINK", civilianGloss: "huge K-pop girl group", undercover: "TWICE", undercoverGloss: "huge K-pop girl group" },
  { civilian: "BTS", civilianGloss: "global K-pop boy group", undercover: "SEVENTEEN", undercoverGloss: "big K-pop boy group" },
  { civilian: "NewJeans", civilianGloss: "trendy K-pop girl group", undercover: "LE SSERAFIM", undercoverGloss: "trendy K-pop girl group" },
  { civilian: "BABYMONSTER", civilianGloss: "new YG K-pop girl group", undercover: "aespa", undercoverGloss: "SM K-pop girl group" },
  { civilian: "Stray Kids", civilianGloss: "K-pop boy group", undercover: "ATEEZ", undercoverGloss: "K-pop boy group" },
  { civilian: "EXO", civilianGloss: "K-pop boy group", undercover: "NCT", undercoverGloss: "K-pop boy group" },
  { civilian: "Billkin", civilianGloss: "Thai singer-actor (I Told Sunset...)", undercover: "PP Krit", undercoverGloss: "Thai singer-actor, his duo partner" },
  { civilian: "Jeff Satur", civilianGloss: "Thai singer, huge solo hits", undercover: "Billkin", undercoverGloss: "Thai singer-actor" },
  { civilian: "4EVE", civilianGloss: "Thai T-pop girl group", undercover: "PROXIE", undercoverGloss: "Thai T-pop boy group" },
  { civilian: "BNK48", civilianGloss: "Thai idol group (Bangkok)", undercover: "CGM48", undercoverGloss: "Thai idol sister group (Chiang Mai)" },
  { civilian: "Milli", civilianGloss: "Thai rapper, played Coachella", undercover: "F.HERO", undercoverGloss: "Thai rapper / hip-hop boss" },
  { civilian: "YOUNGOHM", civilianGloss: "Thai rapper", undercover: "OG-ANIC", undercoverGloss: "Thai rapper" },
  { civilian: "Bodyslam", civilianGloss: "legendary Thai rock band", undercover: "Cocktail", undercoverGloss: "popular Thai rock band" },
  { civilian: "Three Man Down", civilianGloss: "viral Thai pop-rock band", undercover: "Tilly Birds", undercoverGloss: "viral Thai pop-rock band" },
  { civilian: "Palmy", civilianGloss: "beloved Thai female singer", undercover: "Ink Waruntorn", undercoverGloss: "Thai female pop singer" },
  { civilian: "Bowkylion", civilianGloss: "Thai female singer-songwriter", undercover: "Violette Wautier", undercoverGloss: "Thai-Belgian singer-songwriter" },
  { civilian: "Phum Viphurit", civilianGloss: "Thai indie-pop singer", undercover: "Stamp", undercoverGloss: "Thai indie/pop singer" },
  { civilian: "Atom", civilianGloss: "Thai male pop singer (Chanagun)", undercover: "The TOYS", undercoverGloss: "Thai indie-pop singer" },
  { civilian: "Taylor Swift", civilianGloss: "global pop superstar", undercover: "Olivia Rodrigo", undercoverGloss: "Gen-Z pop star" },
  { civilian: "Billie Eilish", civilianGloss: "moody global pop star", undercover: "Olivia Rodrigo", undercoverGloss: "Gen-Z pop star" },
  { civilian: "Ariana Grande", civilianGloss: "pop diva, big vocals", undercover: "Dua Lipa", undercoverGloss: "dance-pop diva" },
  { civilian: "Ed Sheeran", civilianGloss: "British singer-songwriter", undercover: "Bruno Mars", undercoverGloss: "pop-funk superstar" },
  { civilian: "The Weeknd", civilianGloss: "R&B/pop superstar", undercover: "Bruno Mars", undercoverGloss: "pop-funk superstar" },
  { civilian: "Coldplay", civilianGloss: "stadium rock band", undercover: "Maroon 5", undercoverGloss: "pop-rock band" },

  // ---- Movies / series / anime (Thai + popular in Thailand) ----
  { civilian: "Pee Mak", civilianGloss: "Thai ghost-wife romance film", undercover: "Nang Nak", undercoverGloss: "classic Thai ghost-wife film" },
  { civilian: "Shutter", civilianGloss: "iconic Thai ghost-photo horror", undercover: "Alone", undercoverGloss: "Thai twin-ghost horror (same makers)" },
  { civilian: "Bad Genius", civilianGloss: "Thai exam-cheating thriller", undercover: "The Gifted", undercoverGloss: "Thai gifted-students series" },
  { civilian: "Hormones", civilianGloss: "Thai teen drama series", undercover: "Girl from Nowhere", undercoverGloss: "Thai dark school series (Netflix)" },
  { civilian: "Hunger", civilianGloss: "Thai fine-dining Netflix film", undercover: "Bad Genius", undercoverGloss: "Thai exam-cheating thriller" },
  { civilian: "F4 Thailand", civilianGloss: "Thai remake of Meteor Garden", undercover: "2gether", undercoverGloss: "Thai BL hit series" },
  { civilian: "KinnPorsche", civilianGloss: "Thai mafia BL series", undercover: "TharnType", undercoverGloss: "Thai BL series" },
  { civilian: "I Told Sunset About You", civilianGloss: "acclaimed Thai BL series", undercover: "2gether", undercoverGloss: "Thai BL hit series" },
  { civilian: "Squid Game", civilianGloss: "Korean deadly-games Netflix hit", undercover: "All of Us Are Dead", undercoverGloss: "Korean zombie-school Netflix hit" },
  { civilian: "Crash Landing on You", civilianGloss: "K-drama romance smash", undercover: "Goblin", undercoverGloss: "fantasy K-drama romance" },
  { civilian: "Itaewon Class", civilianGloss: "K-drama underdog story", undercover: "Reply 1988", undercoverGloss: "beloved nostalgic K-drama" },
  { civilian: "Avengers", civilianGloss: "Marvel superhero team movie", undercover: "Justice League", undercoverGloss: "DC superhero team movie" },
  { civilian: "Spider-Man", civilianGloss: "web-slinging superhero", undercover: "Batman", undercoverGloss: "the caped crusader" },
  { civilian: "Iron Man", civilianGloss: "Marvel armored hero", undercover: "Captain America", undercoverGloss: "Marvel shield hero" },
  { civilian: "Harry Potter", civilianGloss: "wizard fantasy saga", undercover: "Lord of the Rings", undercoverGloss: "epic fantasy saga" },
  { civilian: "Fast & Furious", civilianGloss: "car-action franchise", undercover: "John Wick", undercoverGloss: "gun-fu action franchise" },
  { civilian: "Frozen", civilianGloss: "Disney ice-princess film", undercover: "Tangled", undercoverGloss: "Disney long-hair-princess film" },
  { civilian: "Minions", civilianGloss: "yellow sidekicks movie", undercover: "Despicable Me", undercoverGloss: "the franchise they come from" },
  { civilian: "Titanic", civilianGloss: "tragic ship romance", undercover: "The Notebook", undercoverGloss: "tearjerker romance" },
  { civilian: "Doraemon", civilianGloss: "robot-cat anime classic", undercover: "Shin Chan", undercoverGloss: "naughty-kid anime classic" },
  { civilian: "One Piece", civilianGloss: "pirate shonen anime", undercover: "Naruto", undercoverGloss: "ninja shonen anime" },
  { civilian: "Attack on Titan", civilianGloss: "titan-fighting anime", undercover: "Demon Slayer", undercoverGloss: "demon-slaying anime hit" },
  { civilian: "Your Name", civilianGloss: "body-swap anime film", undercover: "Suzume", undercoverGloss: "Makoto Shinkai anime film" },
  { civilian: "Detective Conan", civilianGloss: "kid-detective anime", undercover: "Doraemon", undercoverGloss: "robot-cat anime classic" },
  { civilian: "Pee Nak", civilianGloss: "Thai monk-and-ghost comedy", undercover: "Pee Mak", undercoverGloss: "Thai ghost-wife comedy" },
  { civilian: "The Conjuring", civilianGloss: "haunted-house horror hit", undercover: "Annabelle", undercoverGloss: "creepy-doll spin-off" },
  { civilian: "Spirited Away", civilianGloss: "Ghibli spirit-world film", undercover: "My Neighbor Totoro", undercoverGloss: "Ghibli forest-spirit film" },

  // ---- Viral characters / animals / blind-box toys ----
  { civilian: "Moo Deng", civilianGloss: "viral baby pygmy hippo (Thailand)", undercover: "Moo Toon", undercoverGloss: "Moo Deng's older sibling hippo" },
  { civilian: "Moo Deng", civilianGloss: "viral baby pygmy hippo (Thailand)", undercover: "Pesto", undercoverGloss: "viral chunky baby penguin" },
  { civilian: "Labubu", civilianGloss: "viral toothy blind-box toy", undercover: "Crybaby", undercoverGloss: "viral teary art-toy (Molly)" },
  { civilian: "Butterbear", civilianGloss: "viral Thai cafe mascot bear (Nong Butter)", undercover: "Labubu", undercoverGloss: "viral toothy blind-box toy" },
  { civilian: "Labubu", civilianGloss: "viral toothy blind-box toy", undercover: "Sonny Angel", undercoverGloss: "blind-box baby figurine" },
  { civilian: "Hello Kitty", civilianGloss: "iconic Sanrio cat", undercover: "My Melody", undercoverGloss: "Sanrio bunny in a hood" },
  { civilian: "Cinnamoroll", civilianGloss: "Sanrio white puppy", undercover: "Kuromi", undercoverGloss: "Sanrio mischievous rabbit" },
  { civilian: "Pompompurin", civilianGloss: "Sanrio pudding dog", undercover: "Pochacco", undercoverGloss: "Sanrio sporty puppy" },
  { civilian: "Pikachu", civilianGloss: "iconic electric Pokémon", undercover: "Eevee", undercoverGloss: "evolving Pokémon" },
  { civilian: "Mario", civilianGloss: "Nintendo's red-cap plumber", undercover: "Luigi", undercoverGloss: "Mario's green-cap brother" },
  { civilian: "Rilakkuma", civilianGloss: "lazy Japanese bear character", undercover: "Gudetama", undercoverGloss: "lazy egg character" },

  // ---- Food & drinks (Thai street food, viral eats) ----
  { civilian: "Pad Thai", civilianGloss: "stir-fried rice noodles", undercover: "Pad See Ew", undercoverGloss: "soy stir-fried flat noodles" },
  { civilian: "Tom Yum", civilianGloss: "spicy-sour Thai soup", undercover: "Tom Kha", undercoverGloss: "coconut Thai soup" },
  { civilian: "Som Tam", civilianGloss: "spicy green papaya salad", undercover: "Larb", undercoverGloss: "spicy Isan minced-meat salad" },
  { civilian: "Moo Ping", civilianGloss: "grilled pork skewers", undercover: "Moo Krata", undercoverGloss: "Thai BBQ-hotpot pork" },
  { civilian: "Mango Sticky Rice", civilianGloss: "mango + sweet sticky rice", undercover: "Khanom Krok", undercoverGloss: "coconut-rice mini pancakes" },
  { civilian: "Cha Yen", civilianGloss: "Thai iced milk tea (orange)", undercover: "Oliang", undercoverGloss: "Thai iced black coffee" },
  { civilian: "Pang Cha", civilianGloss: "viral Thai-tea shaved ice", undercover: "Cha Yen", undercoverGloss: "Thai iced milk tea" },
  { civilian: "Shabu", civilianGloss: "Japanese-style hotpot", undercover: "Mookata", undercoverGloss: "Thai grill-hotpot combo" },
  { civilian: "Khao Man Gai", civilianGloss: "Thai poached chicken rice", undercover: "Khao Mu Daeng", undercoverGloss: "Thai red-pork rice" },
  { civilian: "Green Curry", civilianGloss: "spicy Thai green curry", undercover: "Massaman", undercoverGloss: "mild peanut Thai curry" },
  { civilian: "Boba", civilianGloss: "bubble / pearl milk tea", undercover: "Cha Yen", undercoverGloss: "Thai iced milk tea" },
  { civilian: "Pad Krapow", civilianGloss: "Thai basil stir-fry on rice", undercover: "Pad Kee Mao", undercoverGloss: "spicy 'drunken' stir-fried noodles" },
  { civilian: "Durian", civilianGloss: "king of fruits (smelly)", undercover: "Mangosteen", undercoverGloss: "queen of fruits" },
  { civilian: "Khao Soi", civilianGloss: "northern Thai curry noodles", undercover: "Boat Noodles", undercoverGloss: "rich Thai 'boat' noodle soup" },

  // ---- Apps / brands / tech (viral in Thailand) ----
  { civilian: "Shopee", civilianGloss: "orange shopping app", undercover: "Lazada", undercoverGloss: "blue shopping app" },
  { civilian: "Grab", civilianGloss: "ride & food delivery app", undercover: "LINE MAN", undercoverGloss: "Thai food delivery app" },
  { civilian: "TikTok", civilianGloss: "short-video app", undercover: "Reels", undercoverGloss: "Instagram's short videos" },
  { civilian: "Facebook", civilianGloss: "the OG social network", undercover: "Instagram", undercoverGloss: "photo-sharing social app" },
  { civilian: "7-Eleven", civilianGloss: "everywhere convenience store", undercover: "Lotus's", undercoverGloss: "Thai supermarket chain" },
  { civilian: "iPhone", civilianGloss: "Apple's phone", undercover: "Samsung", undercoverGloss: "Android phone giant" },
  { civilian: "ChatGPT", civilianGloss: "OpenAI's AI chatbot", undercover: "Gemini", undercoverGloss: "Google's AI chatbot" },
  { civilian: "LINE", civilianGloss: "Thailand's main chat app", undercover: "WhatsApp", undercoverGloss: "global messaging app" },
  { civilian: "Netflix", civilianGloss: "red streaming giant", undercover: "Disney+", undercoverGloss: "Disney's streaming service" },
  { civilian: "Starbucks", civilianGloss: "global coffee chain", undercover: "Café Amazon", undercoverGloss: "Thai PTT coffee chain" },
  { civilian: "YouTube", civilianGloss: "video-sharing platform", undercover: "TikTok", undercoverGloss: "short-video app" },
  { civilian: "Tesla", civilianGloss: "American EV brand", undercover: "BYD", undercoverGloss: "Chinese EV brand (big in TH)" },

  // ---- Sports / icons / misc viral ----
  { civilian: "Messi", civilianGloss: "Argentine football GOAT", undercover: "Ronaldo", undercoverGloss: "Portuguese football GOAT" },
  { civilian: "Bitcoin", civilianGloss: "the original cryptocurrency", undercover: "Dogecoin", undercoverGloss: "the meme cryptocurrency" },
  { civilian: "Mario", civilianGloss: "Nintendo's mascot plumber", undercover: "Sonic", undercoverGloss: "SEGA's speedy blue hedgehog" },
];
